In [1]:
import numpy as np

In [3]:
data = {i : np.random.randn() for i in range(7)}
data

{0: 1.346223931824629,
 1: -0.2928887645131192,
 2: -0.5684110954344629,
 3: 1.0061800456153984,
 4: -0.35231836201344957,
 5: -2.260431483929345,
 6: 0.4733502265507972}

In [6]:
from numpy.random import randn
data = {i : randn() for i in range(7)}
data

{0: -0.6989583967826721,
 1: 0.9390839277572882,
 2: -0.2271735767547275,
 3: -0.7241735943823251,
 4: -1.016614940800759,
 5: -1.1144392542742043,
 6: 0.7358491162657902}

In [ ]:
#x = 365
#Scalar
#rank = 0

#x = [1,2,3,4]
#Vector
#rank = 1
#shape= (4,)

#x = [[1,2,3] , 
     [4,5,6]]# 2행 3열
#Matrix 행렬
#rank = 2
#shape = (2,3)

#x = [[[,]]] #3개 시작 , 3개로 끝
#Cube, 3D
#rank = 3
#shape = ( X , X , X)

In [14]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [15]:
type(a)

numpy.ndarray

In [16]:
a.shape

(3,)

In [17]:
a[0],a[0]

(1, 1)

In [18]:
a[0] =99
a

array([99,  2,  3])

IndexError: too many indices for array

In [20]:
b = np.array([[1,2,3],
              [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b.shape

(2, 3)

In [23]:
b[0,0]

1

In [24]:
c= np.arange(32)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [25]:
c= np.arange(32).reshape(8,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [26]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [27]:
c= np.full((2,2), 8)
c

array([[8, 8],
       [8, 8]])

In [28]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [29]:
a = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [31]:
#새로운 배열이 아닌 레퍼런스 가져오는 방식
b[0,0] = 77
a[0,1]

77

In [35]:
#정수 인덱싱과 슬라이싱을 혼합해서 사용하면 낮는 rank 의 배열이 생성되지만,
#슬라이싱만 사용하면 원본 배열과 동일한 rank 의 배열이 생성됩니다

row1 = a[1, : ] #1번행을 다 가지고 온다. rank가 줄어든다. [5,6,7,8]
row1

row2 = a[1:2, :] #[[5,6,7,8]]
row2

array([[5, 6, 7, 8]])